ngageoint/geopackage-js

- index.js
- lib/db/sqliteAdapter.js
- lib/tiles/creator/index.js
- lib/tiles/retriever/index.js
- lib/tiles/tileBoundingBoxUtils.js
- lib/tiles/user/tileDao.js
- package.json
- static/geopackage.js
- test/lib/tiles/testGeopackageTileRetriever.js
- test/lib/tiles/testTileDao.js
This includes performance improvements when the source and destination projections are the same.
> performance improvements

- .istanbul.yml
- app.css
- includes.css
- index.html
- index.js
- lib/tiles/creator/index.js
- lib/tiles/tileBoundingBoxUtils.js
- lib/tiles/user/tileDao.js
- package.json
- static/geopackage.js
- test/legacy/test.js
- test/lib/tiles/testGeopackageTileRetriever.js
- test/lib/tiles/testTileBoundingBoxUtils.js
- test/lib/tiles/testTileDao.js
pulling in improvements to the demo page
> demo page improvements

- index.html
- index.js
- lib/dataColumns/index.js
- lib/geoPackage.js
This pull adds data column support
> Data Columns

- lib/tiles/creator/tileUtilities.js
> fix undefined errors in tile creator reprojection

- converters/geojson/cli
- converters/geojson/index.js
- converters/geojson/package.json
- converters/geojson/test/testIndex.js
- docs/common.js
- docs/index.html
- docs/index.js
- docs/package.json
- index.js
- lib/db/geoPackageConnection.js
- lib/db/sqliteAdapter.js
- package.json
- test/mocha.opts
- test/testGeopackage.js
This pull includes a GeoJSON converter and integration with the demo page
> GeoJSON converter

- converters/geojson/index.js
- docs/app.css
- docs/common.js
- docs/index.html
- index.js
This pull adds status when importing a GeoJSON file to the demo page.
> adding status when importing geojson

- docs/index.html
- lib/db/geoPackageConnection.js
- lib/db/sqliteAdapter.js
- lib/db/tableCreator.js
- package.json
create web mercator srs by default
> Version 1.0.3 -> 1.0.4

- lib/geom/geometryData.js
- test/lib/geom/testGeometryData.js
fixed a bug where empty was not being set to false
> 1.0.5 -> 1.0.6

- converters/geojson/index.js
- converters/shapefile/index.js
- docs/common.js
Handles the case where the property 'id' is in the shapefile or geojson file already
> handle id property

- converters/shapefile/index.js
- converters/shapefile/test/testIndex.js
- docs/common.js
- index.js
undid dateline wrapping as it was causing other issues
also shape zips don't require a dbf
> undid dateline wrapping as it was causing other issues

- converters/mbtiles/index.js
- converters/mbtiles/package.json
- converters/mbtiles/test/testIndex.js
- converters/pbf/index.js
- converters/pbf/test/testIndex.js
- docs/common.js
- docs/index.js
- index.js
- lib/dao/dao.js
- lib/db/geoPackageConnection.js
- lib/db/sqliteQueryBuilder.js
- lib/db/sqljsAdapter.js
- lib/user/userTable.js
- package.json
- test/fixtures/testSetup.js
- test/lib/issues/68.js
- test/lib/tiles/testGeopackageTileRetriever.js
> PBF MBTiles files conversion

- converters/mbtiles/index.js
- converters/mbtiles/package.json
- converters/mbtiles/test/testIndex.js
- converters/pbf/index.js
- converters/pbf/package.json
- converters/pbf/test/testIndex.js
- lib/db/sqljsAdapter.js
improves the conversion between MBTiles and GeoPackage and PBF and GeoPackage
> Fixing MBTiles and PBF conversions

- index.js
- package.json
Bumping version and removing converters from the main package.
> version 1.0.9

- docs/common.js
> Minor docs fix

- index.js
Exporting GeoPackageManager module in index.js so that the sample code on readme could work.
> Exporting GeoPackageManager module

- package.json
Fails with same error as gotwarlost/istanbul#90
> Failed on Win10. See istanbul issue #90

- converters/shapefile/index.js
> Webpack hack for Proj4

- index.js
- lib/core/srs/index.js
- lib/dao/dao.js
- lib/db/sqliteAdapter.js
- lib/db/sqliteQueryBuilder.js
- lib/extension/index/featureTableIndex.js
- lib/extension/index/geometryIndex.js
- lib/features/user/featureRow.js
- lib/user/userRow.js
- package-lock.json
- package.json
- test/lib/dataColumns/testDataColumns.js
- test/lib/extension/index/testFeatureTableIndex.js
- test/lib/features/user/testFeatureDao.js
- test/lib/testFeatureCreate.js
- test/lib/testTileCreate.js
- test/testGeopackage.js
Upgrade node-sqlite3 to better-sqlite3 in preparation for promises
> Upgrade node-sqlite3 to better-sqlite3

- lib/db/tableCreator.js
- lib/extension/contents/contentsId.js
- lib/extension/contents/index.js
- lib/geoPackage.js
- test/fixtures/verification.js
- test/lib/extension/contents/testContentsIdDao.js
- test/test.js
Added contents id extension and provided unit tests to verify functionality.
contents id extension: http://ngageoint.github.io/GeoPackage/docs/extensions/contents-id.html
This extension is needed for adding style extension.
> added contents id extension and associated unit tests

- lib/tiles/features/index.js
found bug where indexed feature tiles were not grabbing feature styles correctly
> fix for feature style bug

- lib/core/srs/spatialReferenceSystemDao.ts
- lib/geoPackage.ts
- package.json
Creates getByOrganizationAndCoordSysId in lib/core/srs/spatialRefenceSystemDao.ts
In lib/geoPackage.ts
Creates createStandardWebMercatorTileTableWithZoomLevels(), createStandardWebMercatorTileMatrixWithZoomLevels() and createTileMatrixRow
Changes createStandardWebMercatorTileTable() to handle non-webmercator bounding boxes.
Changes createStandardWebMercatorTileMatrix()
> Tile table improvement

- README.md
- lib/features/user/featureDao.ts
Take in account de id property on queryForGeoJSONIndexedFeaturesWithBoundingBox method to create GeoJSON with id property from feature property
> GeoJSON id from feature id property
